### ISSUE TITLE
Discussion on Spatial Pruning in 3D Object Detection

### ISSUE THREAD

**Issue by yukang2017** [xuxw98/DSPDet3D#1]
Hi,

Thanks for your great work! This is a kind discussion on spatial pruning in 3D object detection.

`Dynamic spatial pruning` has been explored in 3D outdoor object detection in our NeurIPS 2022 Paper as shown in below. We understand that there might be many differences in details and designs. But it is still really related. It would be much appreciated if our work could be referenced and discussed in your great work!

Below is the information for our work, Spatial Pruned Sparse Convolution for Efficient 3D Object Detection.

**Paper**: https://proceedings.neurips.cc/paper_files/paper/2022/file/2ce10f144bb93449767f355c01f24cc1-Paper-Conference.pdf
**Code**: https://github.com/CVMI-Lab/SPS-Conv
**Bibtex**:
```
@inproceedings{liu2022spatial,
  title={Spatial Pruned Sparse Convolution for Efficient 3D Object Detection},
  author={Liu, Jianhui and Chen, Yukang and Ye, Xiaoqing and Tian, Zhuotao and Tan, Xiao and Qi, Xiaojuan},
  booktitle={Advances in Neural Information Processing Systems},
  year={2022}
}

```

Thanks for your consideration.

Regards,
Yukang Chen

**Comment by xuxw98** [comment]
Hi YuKang,
Thank for your kind suggestion! The SPS-Conv proposed in your great work is really related to ours, and we will add a discussion in the future version of DSPDet3D.

In my opinion, although both works use the term "dynamic spatial pruning" and aim to reduce unnecessary computation in sparse convolution, there are some fundamental differences. For example:
1. Target. SPS-Conv focuses on suppressing computation on background points, while DSPDet3D aims to remove regions where no smaller object in next level.
2. Framework. DSPDet3D is framework-dependant: it is based on a multi-level detection framework where the spatial redundancy is introduced by [generative upsampling](https://github.com/jgwak/GSDN). SPS-Conv is model-agnostic and can be regarded as a basic module. In fact, I think these two methods can be further combined by replace the sparse convolution in our backbone (MinkResNet34) with SPS-Conv. 
3. Design. DSPDet3D directly prunes the multi-level feature maps of decoder by a learnable pruning module, which is supervised by the keeping mask generated from ground-truth bounding boxes. While SPS-Conv prunes computation within convolution module and is trained end-to-end.

We are happy to have more in-depth discussions~

**Comment by yukang2017** [comment]
Many thanks for your reply! This is very clear.
