### ISSUE TITLE
[Bug] in batch_load_scannet_data.py

### ISSUE THREAD

**Issue by zyrant** [xuxw98/DSPDet3D#2]
1. load_scannet_data.py will not return unaligned_bboxes_sem, aligned_bboxes_sem. https://github.com/xuxw98/DSPDet3D/blob/d43f452273d204cf03de84f6dd51cd740f14275e/data/ScanNet-md40/batch_load_scannet_data.py#L40
2. https://github.com/xuxw98/DSPDet3D/blob/d43f452273d204cf03de84f6dd51cd740f14275e/data/ScanNet-md40/batch_load_scannet_data.py#L137 Is this scannet v2 val.txt instead of scannet train.txt?

**Comment by xuxw98** [comment]
Hi,
Thank you for pointing out this typo. We have corrected `batch_load_scannet_data.py`.
