### ISSUE TITLE
KeyError: 'img' for visualization

### ISSUE THREAD

**Issue by hc20** [xuxw98/DSPDet3D#3]
Hello,

Thanks for your work. I want to visualize the results with the following code:

```
python tools/test.py configs/dspdet3d/dspdet3d_toscene-3d-70class.py \
    /home/ubuntu/DSPDet3D-data/dspdet3d_toscene.pth --eval mAP --show \
    --show-dir /home/ubuntu/DSPDet3D/output
```

But I get the following errors:

```
load checkpoint from local path: /home/ubuntu/DSPDet3D-data/dspdet3d_toscene.pth
[                                                  ] 0/800, elapsed: 0s, ETA:

Traceback (most recent call last):
  File "/home/ubuntu/DSPDet3D/tools/test.py", line 168, in <module>
    main()
  File "/home/ubuntu/DSPDet3D/tools/test.py", line 138, in main
    outputs = single_gpu_test(model, data_loader, args.show, args.show_dir)
  File "/home/ubuntu/anaconda3/envs/mmdet3d/lib/python3.8/site-packages/mmdet3d/apis/test.py", line 58, in single_gpu_test
    if batch_size == 1 and isinstance(data['img'][0],
KeyError: 'img'

Process finished with exit code 1
```

Could you please tell me how to solve this problem? Thank you very much for your help.

**Comment by Cherryreg** [comment]
I think you can confirm if it's possible to run through just testing without visualization.
python tools/test.py configs/dspdet3d/dspdet3d_toscene-3d-70class.py  /home/ubuntu/DSPDet3D-data/dspdet3d_toscene.pth --eval mAP
If the instruction does not report an error, the problem should be with the visualization code. The visualization code can refer to the visualization code in TR3D.
Feel free to exchange relevant questions at any time！

**Comment by hc20** [comment]
Thank you very much for your reply! I modify the visualization code and use `model.module.show_results()` to visualize the detection results in Open3D. But I find that the point cloud has no color information, as shown in this figure:
![Image](https://github.com/xuxw98/DSPDet3D/assets/138543987/72115717-92ca-46df-89a5-6da7b7618871)
How to visualize the detection boxes with colorful point cloud like the figures in your paper? Thank you for your help.

**Comment by GlaucoAntonio** [comment]
> ... I modify the visualization code and use `model.module.show_results()` to visualize the detection results in Open3D. 

Please, could you share your modifications to solve this error? Thanks
