### ISSUE TITLE
We would really like to invite you for a technology live about this work~

### ISSUE THREAD

**Issue by autodriving-heart** [xuxw98/DSPDet3D#5]
Hi, we are the team of _Embodied-Intelligence-Heart_. Admired of your extremely impressive achievement, we would like to invite you to share your achievements on our platform!

Currently, we have accumulated a large number of fans in the fields of autonomous driving and embodied AI. They are distributed in over well-known 300 companies and laboratories both domestically and internationally. We have held over 100 open-source sharing sessions in the past two years. We sincerely hope to invite your team to join in a live broadcast. Look forward to your reply!

**WeChat: AIDriver002**
![image](https://github.com/user-attachments/assets/0bc3c7d8-c36f-403c-a64b-ecbe93059726)

**Comment by xuxw98** [comment]
Thank you very much for your kind invitation and for recognizing our work! We are honored by your interest in sharing our achievements with such a distinguished audience. Could you please provide more details regarding the format and content of the live broadcast, as well as the expected time commitment?

**Comment by autodriving-heart** [comment]
Thank you for your reply! We would like to hold an one-hour _(40 mins main content and 20 mins QA)_ open-source technology live in Nov. You can highlight the background, main contribution and achievements of your work. The live time can be negotiated! We are looking forward to this distinguished live!

**Comment by autodriving-heart** [comment]
Hello~Could we hold a technology live in December?

**Comment by xuxw98** [comment]
Yes! My wechat id is xxw981120xxw. Maybe we can discuss the schedule in detail.
